namespace Rewired
{
	internal enum JoystickType
	{
		Unknown = 0,
		Gamepad = 1,
		DualAnalogGamepad = 2,
		SingleAnalogGamepad = 3,
		DigitalGamepad = 4,
		Joystick = 10,
		AnalogJoystick = 11,
		DigitalJoystick = 12,
		Throttle = 20,
		HOTAS = 21,
		FlightYoke = 22,
		FlightPedals = 23,
		ThrottleQuadrant = 24,
		TrimWheel = 25,
		DrivingWheel = 40,
		Pedals = 41,
		GearShifter = 42,
		Guitar = 50,
		Drums = 51,
		DancePad = 70,
		Paddle = 80,
		Spinner = 81,
		Trackball = 82,
		Gun = 83,
		RemoteControl = 100,
		PointingDevice = 101,
		ShipController = 120,
		TrainController = 121,
		HelicopterController = 122,
		FootController = 123,
		ControlPanel = 140,
		Keypad = 141,
		VRController = 150,
	}
}
